# Injected by GitHubConfigProperties
github.login=${GITHUB_LOGIN:dummy}
github.oauth=${GITHUB_OAUTH:unset-token}

# GitHub GraphQL (SmallRye GraphQL client, see: https://quarkus.io/guides/smallrye-graphql-client
quarkus.smallrye-graphql-client.github-graphql.url=https://api.github.com/graphql
quarkus.smallrye-graphql-client.github-graphql.header.Authorization=Bearer ${github.oauth}
quarkus.smallrye-graphql-client.github-graphql.header.Accept=application/vnd.github+json

quarkus.native.resources.includes=graphql/queries/*.graphql
