package com.garethahealy.githubstats.commands.users;

import com.garethahealy.githubstats.services.users.CollectMembersFromRedHatLdapService;
import freemarker.template.TemplateException;
import jakarta.enterprise.context.Dependent;
import jakarta.inject.Inject;
import org.apache.directory.api.ldap.model.exception.LdapException;
import picocli.CommandLine;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.ExecutionException;

@Dependent
@CommandLine.Command(name = "collect-members-from-ldap", mixinStandardHelpOptions = true, description = "Creates a CSV containing members who have added their GitHub ID to LDAP so we can map who someone is from GitHub to Red Hat")
public class CollectMembersFromRedHatLdapCommand implements Runnable {

    @CommandLine.Option(names = {"-org", "--organization"}, description = "GitHub organization", required = true)
    String organization;

    @CommandLine.Option(names = {"-o", "--csv-output"}, description = "Output location for generated known members CSV", defaultValue = "ldap-members.csv")
    String output;

    @CommandLine.Option(names = {"-i", "--ldap-members-csv"}, description = "CSV of known members, generated by this command previously", defaultValue = "ldap-members.csv")
    String ldapMembersCsv;

    @CommandLine.Option(names = {"-s", "--supplementary-csv"}, description = "CSV of known members collected manually or via the google form", defaultValue = "supplementary.csv")
    String supplementaryCsv;

    @CommandLine.Option(names = {"-g", "--guess"}, description = "Attempt to guess users we cant look up via InfoSec LDAP", defaultValue = "false")
    boolean shouldGuess;

    @CommandLine.Option(names = {"-vpn", "--fail-if-no-vpn"}, description = "Throw an exception if can't connect to LDAP", defaultValue = "true")
    boolean failNoVpn;

    @Inject
    CollectMembersFromRedHatLdapService collectMembersFromRedHatLdapService;

    @Override
    public void run() {
        try {
            if (!Files.exists(Path.of(output))) {
                throw new FileNotFoundException("--csv-output=" + output + " not found.");
            }

            if (!Files.exists(Path.of(ldapMembersCsv))) {
                throw new FileNotFoundException("--ldap-members-csv=" + ldapMembersCsv + " not found.");
            }

            if (!Files.exists(Path.of(supplementaryCsv))) {
                throw new FileNotFoundException("--supplementary-csv=" + supplementaryCsv + " not found.");
            }

            collectMembersFromRedHatLdapService.run(organization, output, ldapMembersCsv, supplementaryCsv, shouldGuess, failNoVpn);
        } catch (IOException | LdapException | TemplateException | ExecutionException | InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
}