package com.garethahealy.githubstats.commands.users;

import com.garethahealy.githubstats.services.users.CollectMembersFromRedHatLdapService;
import freemarker.template.TemplateException;
import jakarta.inject.Inject;
import org.apache.directory.api.ldap.model.exception.LdapException;
import picocli.CommandLine;

import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.ExecutionException;

@CommandLine.Command(name = "collect-members-from-ldap", mixinStandardHelpOptions = true, description = "Creates a CSV containing members who have added their GitHub ID to LDAP so we can map who someone is from GitHub to Red Hat")
public class CollectMembersFromRedHatLdapCommand implements Runnable {

    @CommandLine.Option(names = {"-org", "--organization"}, description = "GitHub organization", required = true)
    String organization;

    @CommandLine.Option(names = {"-i", "--ldap-members-csv"}, description = "CSV of known members, generated by this command previously", defaultValue = "ldap-members.csv")
    String ldapMembersCsv;

    @CommandLine.Option(names = {"-s", "--supplementary-csv"}, description = "CSV of known members collected manually or via the google form", defaultValue = "supplementary.csv")
    String supplementaryCsv;

    @CommandLine.Option(names = {"-v", "--validate-csv"}, description = "Whether to validate the current CSVs against LDAP", defaultValue = "false")
    boolean validateCsv;

    @CommandLine.Option(names = {"-l", "--user-limit"}, description = "Number of GitHub users to check", defaultValue = "0")
    int limit;

    @CommandLine.Option(names = {"-vpn", "--fail-if-no-vpn"}, description = "Throw an exception if can't connect to LDAP", defaultValue = "true")
    boolean failNoVpn;

    @Inject
    CollectMembersFromRedHatLdapService collectMembersFromRedHatLdapService;

    @Override
    public void run() {
        try {
            if (!Files.exists(Path.of(ldapMembersCsv))) {
                new File(ldapMembersCsv).createNewFile();
            }

            if (!Files.exists(Path.of(supplementaryCsv))) {
                new File(supplementaryCsv).createNewFile();
            }

            collectMembersFromRedHatLdapService.run(organization, new File(ldapMembersCsv), new File(supplementaryCsv), validateCsv, limit, failNoVpn);
        } catch (IOException | LdapException | TemplateException |
                    ExecutionException | InterruptedException | URISyntaxException e) {
            throw new RuntimeException(e);
        }
    }
}
