package com.garethahealy.githubstats.commands.users;

import com.garethahealy.githubstats.services.users.ConfigYamlMemberInRedHatLdapService;
import freemarker.template.TemplateException;
import jakarta.enterprise.context.Dependent;
import jakarta.inject.Inject;
import org.apache.directory.api.ldap.model.exception.LdapException;
import picocli.CommandLine;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

@Dependent
@CommandLine.Command(name = "configyaml-member-in-ldap", mixinStandardHelpOptions = true, description = "Creates a single issue containing any users that are part of the GitHub Org but not in LDAP anymore, i.e.: have left Red Hat")
public class ConfigYamlMemberInRedHatLdapCommand implements Runnable {

    @CommandLine.Option(names = {"-o", "--source-org"}, description = "Source organization for changed config.yaml", required = true)
    String sourceOrg;

    @CommandLine.Option(names = {"-r", "--source-repo"}, description = "Source repository for changed config.yaml", required = true)
    String sourceRepo;

    @CommandLine.Option(names = {"-b", "--source-branch"}, description = "Source branch for changed config.yaml", required = true)
    String sourceBranch;

    @CommandLine.Option(names = {"-i", "--ldap-members-csv"}, description = "CSV of known members, generated by 'collect-members-from-ldap'", defaultValue = "ldap-members.csv")
    String ldapMembersCsv;

    @CommandLine.Option(names = {"-s", "--supplementary-csv"}, description = "CSV of known members collected manually or via the google form", defaultValue = "supplementary.csv")
    String supplementaryCsv;

    @CommandLine.Option(names = {"-vpn", "--fail-if-no-vpn"}, description = "Throw an exception if can't connect to LDAP", defaultValue = "true")
    boolean failNoVpn;

    @Inject
    ConfigYamlMemberInRedHatLdapService configYamlMemberInRedHatLdapService;

    @Override
    public void run() {
        try {
            if (!Files.exists(Path.of(ldapMembersCsv))) {
                throw new FileNotFoundException("--ldap-members-csv=" + ldapMembersCsv + " not found.");
            }

            if (!Files.exists(Path.of(supplementaryCsv))) {
                throw new FileNotFoundException("--supplementary-csv=" + supplementaryCsv + " not found.");
            }

            configYamlMemberInRedHatLdapService.run(sourceOrg, sourceRepo, sourceBranch, ldapMembersCsv, supplementaryCsv, failNoVpn);
        } catch (IOException | LdapException | TemplateException e) {
            throw new RuntimeException(e);
        }
    }
}