package com.garethahealy.githubstats.commands.users;

import com.garethahealy.githubstats.services.users.GitHubMemberInRedHatLdapService;
import freemarker.template.TemplateException;
import jakarta.enterprise.context.Dependent;
import jakarta.inject.Inject;
import org.apache.directory.api.ldap.model.exception.LdapException;
import picocli.CommandLine;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

@Dependent
@CommandLine.Command(name = "github-member-in-ldap", mixinStandardHelpOptions = true, description = "Creates a single issue containing any users that are part of the GitHub Org but not in LDAP anymore, i.e.: have left Red Hat")
public class GitHubMemberInRedHatLdapCommand implements Runnable {

    @CommandLine.Option(names = {"-org", "--organization"}, description = "GitHub organization", required = true)
    String organization;

    @CommandLine.Option(names = {"-repo", "--issue-repo"}, description = "Repo where the issues should be created, i.e.: 'org'")
    String orgRepo;

    @CommandLine.Option(names = {"-dry", "--dry-run"}, description = "Dry-run aka don't actually create the GitHub issue", required = true)
    boolean dryRun;

    @CommandLine.Option(names = {"-i", "--ldap-members-csv"}, description = "CSV of known members, generated by 'collect-members-from-ldap'", defaultValue = "ldap-members.csv")
    String ldapMembersCsv;

    @CommandLine.Option(names = {"-s", "--supplementary-csv"}, description = "CSV of known members collected manually or via the google form", defaultValue = "supplementary.csv")
    String supplementaryCsv;

    @CommandLine.Option(names = {"-vpn", "--fail-if-no-vpn"}, description = "Throw an exception if can't connect to LDAP", defaultValue = "true")
    boolean failNoVpn;

    @Inject
    GitHubMemberInRedHatLdapService gitHubMemberInRedHatLdapService;

    @Override
    public void run() {
        try {
            if (!Files.exists(Path.of(ldapMembersCsv))) {
                throw new FileNotFoundException("--ldap-members-csv=" + ldapMembersCsv + " not found.");
            }

            if (!Files.exists(Path.of(supplementaryCsv))) {
                throw new FileNotFoundException("--supplementary-csv=" + supplementaryCsv + " not found.");
            }

            if (!dryRun && (orgRepo == null || orgRepo.isEmpty())) {
                throw new IllegalArgumentException("--dry-run=" + dryRun + " but --issue-repo=" + orgRepo + " - 'issue-repo' cant be empty if 'dry-run' is false");
            }

            gitHubMemberInRedHatLdapService.run(organization, orgRepo, dryRun, ldapMembersCsv, supplementaryCsv, failNoVpn);
        } catch (IOException | LdapException | TemplateException e) {
            throw new RuntimeException(e);
        }
    }
}