package com.garethahealy.githubstats.commands.users;

import com.garethahealy.githubstats.services.users.MembersToSupplementaryDiffService;
import jakarta.enterprise.context.Dependent;
import jakarta.inject.Inject;
import picocli.CommandLine;

import java.io.IOException;

@Dependent
@CommandLine.Command(name = "members-to-supplementary-diff", mixinStandardHelpOptions = true, description = "Check the diff between the two CSVs")
public class MembersToSupplementaryDiffCommand implements Runnable {

    @CommandLine.Option(names = {"-i", "--members-csv"}, description = "CSV of current known members", required = true)
    String membersCsv;

    @CommandLine.Option(names = {"-s", "--supplementary-csv"}, description = "CSV of current known members, generated by 'collect-members-from-ldap'", required = true)
    String supplementaryCsv;

    @Inject
    MembersToSupplementaryDiffService membersToSupplementaryDiffService;

    @Override
    public void run() {
        try {
            membersToSupplementaryDiffService.run(membersCsv, supplementaryCsv);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}